# jwt configuration
jwt:
    signing-key: 'source-manager'

# mysql connect configuration
mysql:
    username: root
    password: '123456'
    path: '127.0.0.1:3307'
    db-name: 'four_seas'
    config: 'charset=utf8&parseTime=True&loc=Local'
    max-idle-conns: 10
    max-open-conns: 10
    log-mode: false

# redis configuration
redis:
    addr: '127.0.0.1:6379'
    password: ''
    db: 0

# system configuration
system:
    use-multipoint: false
    env: 'public'  # Change to "develop" to skip authentication for development mode
    addr: 8888

# captcha configuration
captcha:
    key-long: 6
    img-width: 240
    img-height: 80

# logger configuration
log:
    prefix: '[SOURCE-MANAGER-ADMIN-API]'
    log-file: true
    stdout: 'DEBUG'
    file: 'DEBUG'